import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';
import { basename, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { resolveRuntimeDeployPlugin } from './scripts/runtime-deploy-plugin.mjs';
import { createTpsRuntimeNamespaceEsbuildPlugin } from './scripts/tps-runtime-namespace.mjs';

const projectRoot = dirname(fileURLToPath(import.meta.url));
const sourceFolder = basename(projectRoot);
const runtimeDeployPlugin = await resolveRuntimeDeployPlugin(sourceFolder, import.meta.url);

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';
const nodeBuiltins = builtinModules.flatMap(moduleName =>
    moduleName.startsWith('node:') ? [moduleName] : [moduleName, `node:${moduleName}`]
);

const context = await esbuild.context({
    banner: {
        js: banner
    },
    entryPoints: ['src/main.ts'],
    bundle: true,
    define: {
        'process.env.NODE_ENV': prod ? '"production"' : '"development"'
    },
    external: [
        'obsidian',
        'electron',
        '@codemirror/autocomplete',
        '@codemirror/collab',
        '@codemirror/commands',
        '@codemirror/language',
        '@codemirror/lint',
        '@codemirror/search',
        '@codemirror/state',
        '@codemirror/view',
        '@lezer/common',
        '@lezer/highlight',
        '@lezer/lr',
        ...nodeBuiltins
    ],
    format: 'cjs',
    target: 'es2022',
    charset: 'utf8',
    logLevel: 'info',
    sourcemap: prod ? false : 'inline',
    treeShaking: true,
    outfile: 'main.js',
    minify: prod,
    plugins: [createTpsRuntimeNamespaceEsbuildPlugin(projectRoot), runtimeDeployPlugin]
});

if (prod) {
    await context.rebuild();
    process.exit(0);
} else {
    await context.watch();
}
